// GameCalendar.cs
using System;

namespace TextRPG
{
    public class GameCalendar
    {
        private int Day { get; set; } = 1;
        private int Season { get; set; } = 1;
        private int Year { get; set; } = 1;
        private string[] Seasons = { "Winter", "Spring", "Summer", "Fall" };
        private Random Random = new Random();
        
        private string CurrentSeason { get; set; } = "Spring";
        private bool SeasonChanged { get; set; } = false;
        
        // Action tracking for day advancement
        private int ActionsUntilNewDay { get; set; }
        private const int MIN_ACTIONS_PER_DAY = 6;
        private const int MAX_ACTIONS_PER_DAY = 8;
        private int ActionsSinceLastManaRegen { get; set; } = 0;
        private const int ACTIONS_FOR_MANA_REGEN = 8;
        private const int MANA_REGEN_AMOUNT = 15;
        
        // Quest templates for each season
        private Dictionary<string, List<(string name, string description, int difficulty)>> SeasonalQuestTemplates = new Dictionary<string, List<(string, string, int)>>();

        // Event handler for season changes
        public event Action? OnSeasonChanged;

        private Display Display { get; }
        private Character Player { get; }

        public GameCalendar(Display display, Character player)
        {
            Display = display;
            Player = player;
            InitializeQuestTemplates();
            ResetActionsUntilNewDay();
            UpdateSeason();
        }

        private void ResetActionsUntilNewDay()
        {
            ActionsUntilNewDay = Random.Next(MIN_ACTIONS_PER_DAY, MAX_ACTIONS_PER_DAY + 1);
        }

        public void RecordAction(bool isCombatAction = false)
        {
            ActionsUntilNewDay--;
            
            // Only increment mana regeneration counter for non-combat actions
            if (!isCombatAction)
            {
                ActionsSinceLastManaRegen++;

                // Check for mana regeneration
                if (ActionsSinceLastManaRegen >= ACTIONS_FOR_MANA_REGEN)
                {
                    Player.Mana = Math.Min(Player.Mana + MANA_REGEN_AMOUNT, Player.MaxMana);
                    Display?.displayString($"\nYour mana has regenerated by {MANA_REGEN_AMOUNT} points!");
                    ActionsSinceLastManaRegen = 0;
                }
            }

            if (ActionsUntilNewDay <= 0)
            {
                AdvanceDay();
                Display?.displayString($"\nA new day has dawned. {GetDateString()}");
                ResetActionsUntilNewDay();
            }
        }

        public int GetActionsUntilNewDay()
        {
            return ActionsUntilNewDay;
        }

        private void InitializeQuestTemplates()
        {
            SeasonalQuestTemplates = new Dictionary<string, List<(string, string, int)>>
            {
                ["Winter"] = new List<(string, string, int)>
                {
                    ("Ice Harvesting", "Collect 10 ice crystals from the frozen lake.", 1),
                    ("Winter Wolf Hunt", "Defeat the alpha winter wolf that's been terrorizing travelers.", 2),
                    ("Lost in Blizzard", "Find and rescue the merchant's caravan lost in the snowstorm.", 3),
                    ("Frost Giant's Treasure", "Infiltrate the frost giant's lair and steal his treasure.", 3)
                },
                
                ["Spring"] = new List<(string, string, int)>
                {
                    ("Flower Collection", "Gather rare spring flowers for the town alchemist.", 1),
                    ("Spring Cleaning", "Clear out the vermin that have infested the town granary.", 1),
                    ("River Rescue", "Save villagers from the flooding river banks.", 2),
                    ("Spring Sprite Hunt", "Track down and capture the mischievous spring sprite.", 3)
                },
                
                ["Summer"] = new List<(string, string, int)>
                {
                    ("Heat Wave", "Deliver water to farmers suffering from the drought.", 1),
                    ("Forest Fire", "Help contain the wildfire threatening the eastern woods.", 2),
                    ("Beach Cleanup", "Clear dangerous creatures from the swimming cove.", 2),
                    ("Dragon's Breath", "Collect scales from the fire dragon that appears only in summer.", 3)
                },
                
                ["Fall"] = new List<(string, string, int)>
                {
                    ("Harvest Help", "Assist farmers with bringing in their harvest before winter.", 1),
                    ("Mushroom Hunt", "Gather rare autumn mushrooms from the enchanted forest.", 2),
                    ("Scarecrow Defense", "Protect the fields from the animated scarecrows.", 2),
                    ("Autumn Spirit", "Appease the ancient autumn spirit with a special ritual.", 3)
                }
            };
        }

        public void AdvanceDay()
        {
            Day++;
            if (Day > 30)
            {
                Day = 1;
                Season++;
                if (Season > 4)
                {
                    Season = 1;
                    Year++;
                }
                UpdateSeason();
            }
        }

        private void UpdateSeason()
        {
            string newSeason = Season switch
            {
                1 => "Spring",
                2 => "Summer",
                3 => "Fall",
                4 => "Winter",
                _ => CurrentSeason
            };

            if (newSeason != CurrentSeason)
            {
                SeasonChanged = true;
                CurrentSeason = newSeason;
                OnSeasonChanged?.Invoke(); // Trigger the season change event
            }
        }

        public string GetDateString()
        {
            return $"Year {Year}, {CurrentSeason}, Day {Day}";
        }

        public string GetCurrentSeason() => CurrentSeason;

        public bool HasSeasonChanged()
        {
            if (SeasonChanged)
            {
                SeasonChanged = false;
                return true;
            }
            return false;
        }

        public string[] GetAllSeasons() => new[] { "Spring", "Summer", "Fall", "Winter" };

        // Generate seasonal enemy types based on current season
        public string[] GetSeasonalEnemyTypes()
        {
            switch (CurrentSeason)
            {
                case "Winter":
                    return new[] { "Ice Wolf", "Frost Goblin", "Snow Elemental" };
                case "Spring":
                    return new[] { "Forest Sprite", "Mud Golem", "Pollen Wisp" };
                case "Summer":
                    return new[] { "Fire Lizard", "Sand Scorpion", "Heat Mirage" };
                case "Fall":
                    return new[] { "Leaf Elemental", "Harvest Golem", "Scarecrow" };
                default:
                    return new[] { "Goblin", "Skeleton", "Bandit" };
            }
        }

        // Get seasonal multipliers for enemy stats
        public (float health, float attack, float defense) GetSeasonalEnemyMultipliers()
        {
            switch (CurrentSeason)
            {
                case "Winter":
                    return (1.2f, 0.9f, 1.3f); // Tougher, slower, more defensive
                case "Spring":
                    return (1.0f, 1.0f, 1.0f); // Balanced
                case "Summer":
                    return (0.9f, 1.3f, 0.8f); // Weaker, faster, less defensive
                case "Fall":
                    return (1.1f, 1.1f, 1.0f); // Slightly tougher and stronger
                default:
                    return (1.0f, 1.0f, 1.0f);
            }
        }

        // Generate a list of available quests based on the current season
        public List<SeasonalQuest> GenerateAvailableQuests(int count = 3)
        {
            List<SeasonalQuest> availableQuests = new List<SeasonalQuest>();
            
            // Always include at least one quest from the current season
            var currentSeasonTemplates = SeasonalQuestTemplates[CurrentSeason];
            var template = currentSeasonTemplates[Random.Next(currentSeasonTemplates.Count)];
            
            // Base rewards on difficulty (1-3 stars)
            int expReward = template.difficulty * 50 + Random.Next(10, 30);
            int goldReward = template.difficulty * 30 + Random.Next(5, 20);
            
            availableQuests.Add(new SeasonalQuest(
                template.name, 
                template.description, 
                expReward, 
                goldReward, 
                CurrentSeason, 
                template.difficulty,
                this));
            
            // Fill remaining slots with random quests from any season
            List<string> allSeasons = new List<string>(Seasons);
            
            for (int i = 1; i < count; i++)
            {
                string randomSeason = allSeasons[Random.Next(allSeasons.Count)];
                var seasonTemplates = SeasonalQuestTemplates[randomSeason];
                template = seasonTemplates[Random.Next(seasonTemplates.Count)];
                
                // Base rewards on difficulty (1-3 stars)
                expReward = template.difficulty * 50 + Random.Next(10, 30);
                goldReward = template.difficulty * 30 + Random.Next(5, 20);
                
                availableQuests.Add(new SeasonalQuest(
                    template.name, 
                    template.description, 
                    expReward, 
                    goldReward, 
                    randomSeason, 
                    template.difficulty,
                    this));
            }
            
            return availableQuests;
        }
    }
}